PhotoBlog/Models/BlogPost.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PhotoBlog.Models
{
    public class BlogPost
    {
        public BlogPost()
        {
            this.Tags = new HashSet<HashTag>();
        }
        public int Id { get; set; }
        [Required]
        public string Title { get; set; }
        public string Content { get; set; }
        public string PhotoPath { get; set; }
        public DateTime? CreatingTime { get; set; }
        public virtual ICollection<HashTag> Tags { get; set; }
    }
}

PhotoBlog/Areas/Admin/Controllers/BlogPostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PhotoBlog.Models;

namespace PhotoBlog.Areas.Admin.Controllers
{
    public class BlogPostsController : AdminBaseController
    {

        public ActionResult Index()
        {
            return View(db.BlogPosts.ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.BlogPosts.Find(id);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            return View(blogPost);
        }

        public ActionResult Create()
        {
            ViewBag.Tags = new MultiSelectList(db.HashTags.ToList(), "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BlogPost blogPost, HttpPostedFileBase photo, string[] tags)
        {
            ViewBag.Tags = new MultiSelectList(db.HashTags.ToList(), "Id", "Name");
            PhototErrorControls(photo);
            if (blogPost != null && photo!= null)
            {
                var allTags = tags[1];
                string[] tagFinal = allTags.Split(',');
                for (int i = 0; i < tagFinal.Length; i++)
                {
                    var oneTag = tagFinal[i];
                    if (!db.HashTags.Any(x=>x.Name == oneTag))
                    {
                        HashTag addedTag = new HashTag() { Name = tagFinal[i] };
                        db.HashTags.Add(addedTag);
                        blogPost.Tags.Add(addedTag);
                    }
                    else
                    {
                        HashTag tagAlreadyCreated = db.HashTags.FirstOrDefault(x => x.Name == oneTag);
                        blogPost.Tags.Add(tagAlreadyCreated);
                    }
                }
                blogPost.CreatingTime = DateTime.Now;
                blogPost.PhotoPath = PhotoUpdate(photo);
                db.BlogPosts.Add(blogPost);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(blogPost);
        }


        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.BlogPosts.Find(id);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            ViewBag.tags = blogPost.Tags.ToList();
            return View(blogPost);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Content,PhotoPath,CreatingTime")] BlogPost blogPost, HttpPostedFileBase photo, string[] tags)
        {
            PhototErrorControls(photo);
            if (blogPost != null && photo != null)
            {
                var allTags = tags[1];
                string[] tagFinal = allTags.Split(',');
                for (int i = 0; i < tagFinal.Length; i++)
                {
                    var oneTag = tagFinal[i];
                    if (!db.HashTags.Any(x => x.Name == oneTag))
                    {
                        HashTag addedTag = new HashTag() { Name = tagFinal[i] };
                        db.HashTags.Add(addedTag);
                        blogPost.Tags.Add(addedTag);
                    }
                    else
                    {
                        HashTag tagAlreadyCreated = db.HashTags.FirstOrDefault(x => x.Name == oneTag);
                        blogPost.Tags.Add(tagAlreadyCreated);
                    }
                }

                var photoPath = PhotoUpdate(photo);
                if (photoPath != null)
                {
                    DeletePhoto(blogPost.PhotoPath);
                    blogPost.PhotoPath = photoPath;
                }
                db.Entry(blogPost).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(blogPost);
        }


        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.BlogPosts.Find(id);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            return View(blogPost);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BlogPost blogPost = db.BlogPosts.Find(id);
            db.BlogPosts.Remove(blogPost);
            db.SaveChanges();
            DeletePhoto(blogPost.PhotoPath);
            return RedirectToAction("Index");
        }

        private void DeletePhoto(string photoPath)
        {
            if (!string.IsNullOrEmpty(photoPath))
            {
                var DelPath = Path.Combine(Server.MapPath("~/Images/Uploads"), photoPath);

                if (System.IO.File.Exists(DelPath))
                {
                    System.IO.File.Delete(DelPath);
                }
            }
        }

        private void PhototErrorControls(HttpPostedFileBase photo)
        {
            string[] alloweds = { ".jpg", ".jpeg", ".png" };
            if (photo != null)
            {
                if (!alloweds.Contains(Path.GetExtension(photo.FileName).ToLower()))
                {
                    ModelState.AddModelError("photo", "İzin verilen dosya uzantıları: .jpg, .jpeg, .png");
                }
                else if (photo.ContentLength > 10000 * 10000)
                {
                    ModelState.AddModelError("photo", "Resim boyutu 100mb'dan küçük olmalıdır");
                }

            }
        }

        private string PhotoUpdate(HttpPostedFileBase photo)
        {
            if (photo == null)
                return null;
            var fileName = Guid.NewGuid().ToString() + Path.GetExtension(photo.FileName);
            var installFilePath = Server.MapPath("~/Images/Uploads");
            var savePath = Path.Combine(installFilePath, fileName);
            photo.SaveAs(savePath);
            return fileName;
        }
    }
}

PhotoBlog/Areas/Admin/Views/BlogPosts/Create.cshtml
@model PhotoBlog.Models.BlogPost

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "BlogPosts", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>BlogPost</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label>Tags</label>
            @Html.TextBoxFor(x => x.Tags, new { @class = "form-control", required = "required", @data_role = "tagsinput" })
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <label for="photo">Photo:</label>
                <input type="file" id="photo" name="photo" />
                @Html.ValidationMessage("photo")
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PhotoBlog/Areas/Admin/Views/BlogPosts/Delete.cshtml
@model PhotoBlog.Models.BlogPost

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BlogPost</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhotoPath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhotoPath)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatingTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatingTime)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PhotoBlog/Areas/Admin/Views/BlogPosts/Details.cshtml
@model PhotoBlog.Models.BlogPost

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>BlogPost</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhotoPath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhotoPath)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatingTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatingTime)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PhotoBlog/Areas/Admin/Views/BlogPosts/Edit.cshtml
@model PhotoBlog.Models.BlogPost

@{
    ViewBag.Title = "Edit";
    var tags = "";
    foreach (var item in ViewBag.Tags)
    {
        tags += item.Name + ",";
    }
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "BlogPosts", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>BlogPost</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.CreatingTime)

    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label>Tags</label>
        @*@Html.TextBoxFor(x => x.Tags, new { @class = "form-control", required = "required", @data_role = "tagsinput" })*@
        <input class="form-control sr-only" data-role="tagsinput" id="Tags" name="Tags" required="required" type="text" value="@tags">
    </div>

    <div class="form-group">
        <div class="col-md-10">
            <label for="photo">Photo:</label>
            <input type="file" id="photo" name="photo" />
            @Html.ValidationMessage("photo")
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PhotoBlog/Areas/Admin/Views/BlogPosts/Index.cshtml
@model IEnumerable<PhotoBlog.Models.BlogPost>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Content)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhotoPath)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatingTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tags)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Title)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Content)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.PhotoPath)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.CreatingTime)
    </td>
    <td>
        @*@Html.DisplayFor(modelItem => item.Tags)*@
        @foreach (var tag in item.Tags)
        {
        <span>@tag.Name</span>
        }
    </td>
    <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
    </td>
</tr>
}

</table>